/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bookstore.gui.components.headers;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;

import com.bookstore.gui.components.books.BrowseProductPanel;
import com.bookstore.gui.components.dashboards.DashboardPanel;
import com.bookstore.gui.components.orders.OrderListPanel;
import com.bookstore.gui.components.users.UserListPanel;

/**
 *
 * @author yanti
 */
public class HeaderAdmin extends javax.swing.JPanel {

  private static HeaderAdmin instance;
  private String namePanel;

  /**
   * Creates new form HeaderForm
   */
  public HeaderAdmin() {
    initComponents();
  }

  public HeaderAdmin(String namePanel) {
    this.namePanel = namePanel;
  }

  public static HeaderAdmin getInstance() {
    if (instance == null) {
      instance = new HeaderAdmin();
    }
    return instance;
  }

  public void setPanelNow(String namePanel) {
    this.namePanel = namePanel;
  }

  public String getPanelNow() {
    return namePanel;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profilePanel = new javax.swing.JPanel();
        buttonProfile = new javax.swing.JLabel();
        buttonSearch = new javax.swing.JButton();
        contend = new javax.swing.JPanel();
        getValueSearch = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMinimumSize(new java.awt.Dimension(688, 44));
        setLayout(new java.awt.BorderLayout(20, 0));

        profilePanel.setBackground(new java.awt.Color(255, 255, 255));
        profilePanel.setLayout(new java.awt.BorderLayout(10, 5));

        buttonProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/avatarAmin.png"))); // NOI18N
        profilePanel.add(buttonProfile, java.awt.BorderLayout.EAST);

        buttonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/search.png"))); // NOI18N
        buttonSearch.setToolTipText("");
        buttonSearch.setBorder(null);
        buttonSearch.setPreferredSize(new java.awt.Dimension(45, 24));
        buttonSearch.addActionListener(new ActionListener() {

          @Override
          public void actionPerformed(ActionEvent e) {
            actionSearch(e);
          }
          
        });
        profilePanel.add(buttonSearch, java.awt.BorderLayout.WEST);

        add(profilePanel, java.awt.BorderLayout.LINE_END);

        contend.setBackground(new java.awt.Color(255, 255, 255));
        contend.setMinimumSize(new java.awt.Dimension(593, 44));
        contend.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        getValueSearch.setPreferredSize(new java.awt.Dimension(200, 22));
        contend.add(getValueSearch);

        add(contend, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonProfile;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JPanel contend;
    private javax.swing.JTextField getValueSearch;
    private javax.swing.JPanel profilePanel;
    // End of variables declaration//GEN-END:variables

  public void actionSearch(ActionEvent e) {
    String value = getValueSearch.getText();
    if (HeaderAdmin.getInstance().getPanelNow().equals("UserList")) {
      UserListPanel.getInstance().receiveValue(value);
    }
    if (HeaderAdmin.getInstance().getPanelNow().equals("DashBoard")) {
      DashboardPanel.getInstance().receiveValue(value);
    }
    if (HeaderAdmin.getInstance().getPanelNow().equals("BookList")) {
      BrowseProductPanel.getInstance().receiveValue(value);
    }
    if (HeaderAdmin.getInstance().getPanelNow().equals("OrderList")) {
      OrderListPanel.getInstance().receiveValue(value);
    }
  }

}