version: "3.8"
services:
  database:
    image: mysql:8.0.32-debian
    container_name: bookstore-database
    restart: always
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=admin123
    ports:
      - "3306:3306"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d/:ro
