/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bookstore.gui.component.book;

import com.bookstore.gui.form.admin.component.book.BookDetailFrame;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

import com.itextpdf.text.Image;

/**
 *
 * @author yanti
 */
public class BookProductPanel extends javax.swing.JPanel {

        private JTextField isbnBook;

        /**
         * Creates new form BookProductPanel
         */
        public BookProductPanel(String isbn, String title, String description, String image, int price, int quantity,
                        Enum status, int publisher_id, int author_id) {
                initComponents(isbn, title, description, image, price, quantity, status, publisher_id, author_id);
                setImage(image);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GetImageBook = new javax.swing.JLabel();
        ButtonDetail = new javax.swing.JButton();
        checkBox = new javax.swing.JCheckBox();
        setName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(201, 246));

        GetImageBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GetImageBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bookstore/gui/admin/imageBook/imagebook1.png"))); // NOI18N
        GetImageBook.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ButtonDetail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonDetail.setText("Detail");

        setName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        setName.setText("name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(setName)
                    .addComponent(GetImageBook, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(checkBox)
                        .addGap(27, 27, 27)
                        .addComponent(ButtonDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(setName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GetImageBook, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBox))
                .addContainerGap(7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

        public void setImage(String image) {
                GetImageBook.setIcon(new javax.swing.ImageIcon(image));
                ImageIcon icon = (ImageIcon) GetImageBook.getIcon();
                int imageLoadStatus = icon.getImageLoadStatus();
                if (imageLoadStatus != 8) {
                        GetImageBook.setIcon(new javax.swing.ImageIcon(
                                        getClass().getResource("/resources/images_products/imagenull.png")));
                }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDetail;
    private javax.swing.JLabel GetImageBook;
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JTextField setName;
    // End of variables declaration//GEN-END:variables
}
