/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bookstore.gui.form.admin.component.userListComponent;

import com.bookstore.bus.UserBUS;
import com.bookstore.models.UserModel;

import java.awt.Component;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.Duration;
import java.time.LocalDateTime;
import java.util.List;
import java.util.concurrent.TimeUnit;

import javax.swing.JCheckBox;
import javax.swing.border.Border;
import javax.swing.*;

/**
 *
 * @author yanti
 */
public class UserComponent extends javax.swing.JPanel implements MouseListener {

  private static UserComponent instance;

  private int quantityAdmin;
  private int quantityCustomer;
  private int quantityUser;
  private int quantityEmployee;

  /**
   * Creates new form UserComponent
   * 
   * @throws SQLException
   * @throws ClassNotFoundException
   */
  private UserComponent() {
    initComponents();
  }

  public static UserComponent getInstance() {
    if (instance == null) {
      instance = new UserComponent();
    }
    return instance;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   * 
   * @return
   * 
   * @throws SQLException
   * @throws ClassNotFoundException
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents

  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();
    EmployeeCart = new javax.swing.JPanel();
    IconEmployee1 = new javax.swing.JLabel();
    TextEmployee1 = new javax.swing.JLabel();
    NewEmployee = new javax.swing.JLabel();
    QuatityEmployee = new javax.swing.JLabel();
    AdminCart = new javax.swing.JPanel();
    IconAdmin1 = new javax.swing.JLabel();
    TextAdmin1 = new javax.swing.JLabel();
    NewAdmin = new javax.swing.JLabel();
    QuatityAdmin = new javax.swing.JLabel();
    CustomerCart = new javax.swing.JPanel();
    IconCustomer1 = new javax.swing.JLabel();
    TextCustomer1 = new javax.swing.JLabel();
    NewCustomer = new javax.swing.JLabel();
    QuatityCustomer = new javax.swing.JLabel();
    jPanel4 = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();
    jPanel7 = new javax.swing.JPanel();
    jPanel8 = new javax.swing.JPanel();
    ButtonExport = new javax.swing.JButton();
    ButtonImport = new javax.swing.JButton();
    ButtonCreate = new javax.swing.JButton();
    ButtonBaned = new javax.swing.JButton();
    jPanel9 = new javax.swing.JPanel();
    AllUser = new javax.swing.JLabel();
    Admin = new javax.swing.JLabel();
    customer = new javax.swing.JLabel();
    employee = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    table = new javax.swing.JPanel();

    jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
    jLabel1.setText("User List");

    jPanel2.setLayout(new java.awt.BorderLayout(0, 5));

    jPanel3.setLayout(new java.awt.GridLayout(1, 0, 50, 0));

    EmployeeCart.setBackground(new java.awt.Color(255, 204, 255));
    EmployeeCart.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    IconEmployee1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/employeeCart.png"))); // NOI18N

    TextEmployee1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    TextEmployee1.setForeground(new java.awt.Color(255, 51, 51));
    TextEmployee1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    TextEmployee1.setText("EMPLOYEE");

    NewEmployee.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
    NewEmployee.setText("New User: 100");

    QuatityEmployee.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
    QuatityEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    QuatityEmployee.setText("10000");

    javax.swing.GroupLayout EmployeeCartLayout = new javax.swing.GroupLayout(EmployeeCart);
    EmployeeCart.setLayout(EmployeeCartLayout);
    EmployeeCartLayout.setHorizontalGroup(
        EmployeeCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeCartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconEmployee1, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EmployeeCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(QuatityEmployee, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextEmployee1, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(EmployeeCartLayout.createSequentialGroup()
                .addComponent(NewEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 114,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)));
    EmployeeCartLayout.setVerticalGroup(
        EmployeeCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeCartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EmployeeCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconEmployee1, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EmployeeCartLayout.createSequentialGroup()
                        .addComponent(TextEmployee1, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QuatityEmployee)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewEmployee)
                .addContainerGap(16, Short.MAX_VALUE)));

    jPanel3.add(EmployeeCart);

    AdminCart.setBackground(new java.awt.Color(220, 207, 189));
    AdminCart.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    AdminCart.setPreferredSize(new java.awt.Dimension(145, 100));

    IconAdmin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/adminCart.png"))); // NOI18N

    TextAdmin1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    TextAdmin1.setForeground(new java.awt.Color(255, 51, 51));
    TextAdmin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    TextAdmin1.setText("ADMIN");

    NewAdmin.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
    NewAdmin.setText("New User: 100");

    QuatityAdmin.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
    QuatityAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    QuatityAdmin.setText("10000");

    javax.swing.GroupLayout AdminCartLayout = new javax.swing.GroupLayout(AdminCart);
    AdminCart.setLayout(AdminCartLayout);
    AdminCartLayout.setHorizontalGroup(
        AdminCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminCartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AdminCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(QuatityAdmin, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextAdmin1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(AdminCartLayout.createSequentialGroup()
                .addComponent(NewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 114,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)));
    AdminCartLayout.setVerticalGroup(
        AdminCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminCartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AdminCartLayout.createSequentialGroup()
                        .addComponent(TextAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QuatityAdmin)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewAdmin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    jPanel3.add(AdminCart);

    CustomerCart.setBackground(new java.awt.Color(242, 149, 158));
    CustomerCart.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    CustomerCart.setPreferredSize(new java.awt.Dimension(145, 100));

    IconCustomer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/customerCart.png"))); // NOI18N

    TextCustomer1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    TextCustomer1.setForeground(new java.awt.Color(255, 51, 51));
    TextCustomer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    TextCustomer1.setText("CUSTOMER");

    NewCustomer.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
    NewCustomer.setText("New User: 100");

    QuatityCustomer.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
    QuatityCustomer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    QuatityCustomer.setText("10000");

    javax.swing.GroupLayout CustomerCartLayout = new javax.swing.GroupLayout(CustomerCart);
    CustomerCart.setLayout(CustomerCartLayout);
    CustomerCartLayout.setHorizontalGroup(
        CustomerCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerCartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconCustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustomerCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(QuatityCustomer, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextCustomer1, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CustomerCartLayout.createSequentialGroup()
                .addComponent(NewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 114,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)));
    CustomerCartLayout.setVerticalGroup(
        CustomerCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerCartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomerCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconCustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CustomerCartLayout.createSequentialGroup()
                        .addComponent(TextCustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QuatityCustomer)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewCustomer)
                .addContainerGap(16, Short.MAX_VALUE)));

    jPanel3.add(CustomerCart);

    jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

    jPanel4.setLayout(new java.awt.BorderLayout());

    jPanel5.setPreferredSize(new java.awt.Dimension(688, 40));
    jPanel5.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

    jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    jPanel7.setPreferredSize(new java.awt.Dimension(110, 60));
    jPanel7.setLayout(new java.awt.BorderLayout());

    ButtonExport.setText("Xuất File");

    ButtonImport.setText("Nhập File");

    ButtonCreate.setText("Create");
    ButtonCreate.addMouseListener(new MouseAdapter() {
      @Override
      public void mouseClicked(MouseEvent e) {
        CreateUserForm createUserForm = new CreateUserForm();
        createUserForm.setVisible(true);
      }

    });

    findAllUser();

    ButtonBaned.setText("Banned");
    ButtonBaned.addMouseListener(new MouseAdapter() {
      @Override
      public void mouseClicked(MouseEvent e) {
        actionDelete();
      }

    });

    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonExport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonImport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonBaned)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    jPanel8Layout.setVerticalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonExport)
                    .addComponent(ButtonImport)
                    .addComponent(ButtonCreate)
                    .addComponent(ButtonBaned))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    jPanel7.add(jPanel8, java.awt.BorderLayout.LINE_END);

    AllUser.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
    AllUser.setForeground(new java.awt.Color(255, 51, 51));
    AllUser.setText("AllUser");

    AllUser.addMouseListener(new MouseAdapter() {
      @Override
      public void mouseClicked(MouseEvent e) {
        findAllUser();
      }

    });

    Admin.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
    Admin.setText("Admin");

    Admin.addMouseListener(new MouseAdapter() {
      @Override
      public void mouseClicked(MouseEvent e) {
        findAdmin();
      }

    });

    customer.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
    customer.setText("Customer");

    customer.addMouseListener(new MouseAdapter() {
      @Override
      public void mouseClicked(MouseEvent e) {
        findCustomer();
      }

    });

    employee.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
    employee.setText("Employee");

    employee.addMouseListener(new MouseAdapter() {
      @Override
      public void mouseClicked(MouseEvent e) {
        findEmployee();
      }

    });

    javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
    jPanel9.setLayout(jPanel9Layout);
    jPanel9Layout.setHorizontalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(AllUser, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Admin)
                .addGap(12, 12, 12)
                .addComponent(customer)
                .addGap(18, 18, 18)
                .addComponent(employee)
                .addGap(0, 102, Short.MAX_VALUE)));
    jPanel9Layout.setVerticalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AllUser)
                    .addComponent(Admin)
                    .addComponent(customer)
                    .addComponent(employee))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    jPanel7.add(jPanel9, java.awt.BorderLayout.LINE_START);

    jPanel5.add(jPanel7);

    jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_START);

    javax.swing.GroupLayout tableLayout = new javax.swing.GroupLayout(table);
    table.setLayout(tableLayout);
    tableLayout.setHorizontalGroup(
        tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE));
    tableLayout.setVerticalGroup(
        tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE));
    findAllUser();
    jScrollPane1.setViewportView(table);
    jScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

    jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

    jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)));
  }// </editor-fold>//GEN-END:initComponents

  public void actionCard() {
    int QuantityAdminNew = 0;
    int QuantityCustomerNew = 0;
    int QuantityEmployeeNew = 0;
    quantityAdmin = 0;
    quantityCustomer = 0;
    quantityEmployee = 0;
    quantityUser = 0;
    List<UserModel> userList = UserBUS.getInstance().getAllModels();
    for (UserModel user : userList) {
      LocalDateTime getTime = user.getCreatedAt();
      LocalDateTime timeNow = LocalDateTime.now();
      Duration duration = Duration.between(getTime, timeNow);
      long daysDiff = duration.toMillis();
      if (!user.getStatus().toString().equals("BANNED")) {
        quantityUser = quantityUser + 1;
        if (user.getRole().toString().equals("ADMIN")) {
          quantityAdmin = quantityAdmin + 1;
          if (daysDiff <= 7) {
            QuantityAdminNew = QuantityAdminNew + 1;
          }
        } else if (user.getRole().toString().equals("EMPLOYEE")) {
          quantityEmployee = quantityEmployee + 1;
          if (daysDiff <= 7) {
            QuantityEmployeeNew = QuantityEmployeeNew + 1;
          }
        } else {
          quantityCustomer = quantityCustomer + 1;
          if (daysDiff <= 7) {
            QuantityCustomerNew = QuantityCustomerNew + 1;
          }
        }
      }
    }
    NewAdmin.setText("New User: " + QuantityAdminNew);
    NewCustomer.setText("New User: " + QuantityCustomerNew);
    NewEmployee.setText("New User: " + QuantityEmployeeNew);

    QuatityAdmin.setText("" + quantityAdmin);
    QuatityCustomer.setText("" + quantityCustomer);
    QuatityEmployee.setText("" + quantityEmployee);

  }

  public void actionDelete() {
    for (Component component : table.getComponents()) {
      JPanel subPanel = (JPanel) component;
      for (Component subComponent : subPanel.getComponents()) {
        if (subComponent instanceof JCheckBox && ((JCheckBox) subComponent).isSelected()) {
          Component[] components = subPanel.getComponents();
          boolean foundTextField = false;
          for (Component c : components) {
            if (c instanceof JTextField && !foundTextField) {
              foundTextField = true;
              System.out.println(((JTextField) c).getText());
              int id = Integer.parseInt(((JTextField) c).getText());
              int deletedRows = UserBUS.getInstance().deleteModel(id);
              if (deletedRows == 1) {
                JOptionPane.showMessageDialog(null, " Khóa Tài Khoản Thành Công !");
              }
            }
          }
        }
      }
    }
    table.revalidate();
    table.repaint();
  }

  public void findAdmin() {

    table.removeAll();
    actionCard();
    table.setLayout(new GridLayout(quantityAdmin, 1));
    int serial = 0;
    List<UserModel> userList = UserBUS.getInstance().getAllModels();
    for (UserModel user : userList) {
      if (user.getRole().toString().equals("ADMIN") && !user.getStatus().toString().equals("BANNED")) {
        UserForm userForm = new UserForm(serial, user.getId(), user.getUsername(), user.getPassword(), user.getStatus(),
            user.getName(), user.getEmail(), user.getPhone(), user.getRole(), user.getCreatedAt(), user.getUpdatedAt());
        table.add(userForm);
        serial++;
      }
    }
    table.revalidate();
    table.repaint();
  }

  public void findCustomer() {
    table.removeAll();
    actionCard();
    table.setLayout(new GridLayout(quantityCustomer, 1));
    int serial = 0;
    List<UserModel> userList = UserBUS.getInstance().getAllModels();
    for (UserModel user : userList) {
      if (user.getRole().toString().equals("CUSTOMER") && !user.getStatus().toString().equals("BANNED")) {
        UserForm userForm = new UserForm(serial, user.getId(), user.getUsername(), user.getPassword(), user.getStatus(),
            user.getName(), user.getEmail(), user.getPhone(), user.getRole(), user.getCreatedAt(), user.getUpdatedAt());
        table.add(userForm);
        serial++;
      }
    }
    table.revalidate();
    table.repaint();
  }

  public void findEmployee() {
    table.removeAll();
    actionCard();
    table.setLayout(new GridLayout(quantityEmployee, 1));
    int serial = 0;
    List<UserModel> userList = UserBUS.getInstance().getAllModels();
    for (UserModel user : userList) {
      if (user.getRole().toString().equals("EMPLOYEE") && !user.getStatus().toString().equals("BANNED")) {
        UserForm userForm = new UserForm(serial, user.getId(), user.getUsername(), user.getPassword(), user.getStatus(),
            user.getName(), user.getEmail(), user.getPhone(), user.getRole(), user.getCreatedAt(), user.getUpdatedAt());
        table.add(userForm);
        serial++;
      }
    }
    table.revalidate();
    table.repaint();
  }

  public void findAllUser() {
    table.removeAll();
    actionCard();
    table.setLayout(new GridLayout(quantityUser, 1));
    List<UserModel> userList = UserBUS.getInstance().getAllModels();
    int serial = 0;
    for (UserModel user : userList) {
      if (!user.getStatus().toString().equals("BANNED")) {
        UserForm userForm = new UserForm(serial, user.getId(), user.getUsername(), user.getPassword(), user.getStatus(),
            user.getName(), user.getEmail(), user.getPhone(), user.getRole(), user.getCreatedAt(), user.getUpdatedAt());
        table.add(userForm);
        serial++;
      }
    }
    table.revalidate();
    table.repaint();
  }

  public void receivevalue(String value) {
    String[] columns = new String[] {"name" };
    table.removeAll();
    List<UserModel> list = UserBUS.getInstance().searchModel(value, columns);
    table.setLayout(new GridLayout(0, 1, 10, 10));
    for (UserModel user : list) {
      if (!user.getStatus().toString().equals("DELETED")) {
        UserForm userForm = new UserForm(1, user.getId(), user.getUsername(), user.getPassword(), user.getStatus(),
            user.getName(), user.getEmail(), user.getPhone(), user.getRole(), user.getCreatedAt(), user.getUpdatedAt());
        table.add(userForm);
      }
    }
    table.revalidate();
    table.repaint();

  }

  private void ButtonBanedActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonBanedActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_ButtonBanedActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel Admin;
  private javax.swing.JPanel AdminCart;
  private javax.swing.JLabel AllUser;
  private javax.swing.JButton ButtonBaned;
  private javax.swing.JButton ButtonCreate;
  private javax.swing.JButton ButtonExport;
  private javax.swing.JButton ButtonImport;
  private javax.swing.JPanel CustomerCart;
  private javax.swing.JPanel EmployeeCart;
  private javax.swing.JLabel IconAdmin1;
  private javax.swing.JLabel IconCustomer1;
  private javax.swing.JLabel IconEmployee1;
  private javax.swing.JLabel NewAdmin;
  private javax.swing.JLabel NewCustomer;
  private javax.swing.JLabel NewEmployee;
  private javax.swing.JLabel QuatityAdmin;
  private javax.swing.JLabel QuatityCustomer;
  private javax.swing.JLabel QuatityEmployee;
  private javax.swing.JLabel TextAdmin1;
  private javax.swing.JLabel TextCustomer1;
  private javax.swing.JLabel TextEmployee1;
  private javax.swing.JLabel customer;
  private javax.swing.JLabel employee;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel7;
  private javax.swing.JPanel jPanel8;
  private javax.swing.JPanel jPanel9;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JPanel table;

  // End of variables declaration//GEN-END:variables
  @Override
  public void mouseClicked(MouseEvent e) {

  }

  @Override
  public void mousePressed(MouseEvent e) {

  }

  @Override
  public void mouseReleased(MouseEvent e) {

  }

  @Override
  public void mouseEntered(MouseEvent e) {

  }

  @Override
  public void mouseExited(MouseEvent e) {

  }
}
