/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bookstore.gui.form.admin.component.userListComponent;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Timestamp;

import javax.swing.JTextField;

import com.bookstore.models.UserModel.Role;
import com.bookstore.models.UserModel.Status;

/**
 *
 * @author yanti
 */
public class UserForm extends javax.swing.JPanel implements MouseListener {

  private JTextField IdUser;

  /**
   * Creates new form UserForm
   */
  public UserForm(int Serial, int idUser, String userName, String password, Status status, String name, String email,
      String phone, Role role, Timestamp dateCreate, Timestamp dateUpdate) {
    initComponents(Serial, idUser, userName, password, status, name, email, phone, role);
    addMouseListener(new MouseAdapter() {
      @Override
      public void mouseClicked(MouseEvent e) {
        PopupUser userFullForm = new PopupUser(idUser, userName, password, status, name, email, phone, role, dateCreate,
            dateUpdate);
        userFullForm.setVisible(true);
      }

    });

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents(int Serial, int idUser, String userName, String password, Status status, String name,
      String email,
      String phone, Role role) {

    stt = new javax.swing.JLabel();
    RoleUser = new javax.swing.JTextField();
    NameUser = new javax.swing.JLabel();
    PhoneUser = new javax.swing.JLabel();
    EmailUser = new javax.swing.JLabel();
    StatusUser = new javax.swing.JTextField();
    jCheckBox1 = new javax.swing.JCheckBox();
    IdUser = new JTextField();

    IdUser.setText("" + idUser);
    add(IdUser);

    stt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    stt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    stt.setText("" + Serial);
    stt.setMaximumSize(new java.awt.Dimension(12, 18));
    stt.setMinimumSize(new java.awt.Dimension(12, 18));
    stt.setName(""); // NOI18N
    stt.setPreferredSize(new java.awt.Dimension(12, 19));

    RoleUser.setEditable(false);
    RoleUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    RoleUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    RoleUser.setText("" + role);
    RoleUser.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        RoleUserActionPerformed(evt);
      }
    });

    NameUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    NameUser.setText(name);

    PhoneUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    PhoneUser.setText(phone);

    EmailUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    EmailUser.setText(email);

    StatusUser.setEditable(false);
    StatusUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    StatusUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    StatusUser.setText("" + status);
    StatusUser.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        StatusUserActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(NameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 115,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED,
                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PhoneUser, javax.swing.GroupLayout.PREFERRED_SIZE, 101,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 141,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RoleUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(StatusUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 53,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(stt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(StatusUser, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(RoleUser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(NameUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE)
            .addComponent(PhoneUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE)
            .addComponent(EmailUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));
  }// </editor-fold>//GEN-END:initComponents

  private void RoleUserActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RoleUserActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_RoleUserActionPerformed

  private void StatusUserActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_StatusUserActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_StatusUserActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel EmailUser;
  private javax.swing.JLabel NameUser;
  private javax.swing.JLabel PhoneUser;
  private javax.swing.JTextField RoleUser;
  private javax.swing.JTextField StatusUser;
  private javax.swing.JCheckBox jCheckBox1;
  private javax.swing.JLabel stt;

  // End of variables declaration//GEN-END:variables
  @Override
  public void mouseClicked(MouseEvent e) {

  }

  @Override
  public void mousePressed(MouseEvent e) {
  }

  @Override
  public void mouseReleased(MouseEvent e) {
  }

  @Override
  public void mouseEntered(MouseEvent e) {
  }

  @Override
  public void mouseExited(MouseEvent e) {
  }

}
