/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bookstore.gui.form.admin.component.book;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.io.File;
import java.util.Arrays;
import java.util.List;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

import com.bookstore.bus.AuthorBUS;
import com.bookstore.bus.BookBUS;
import com.bookstore.bus.PublisherBUS;
import com.bookstore.bus.UserBUS;
import com.bookstore.models.BookModel;
import com.bookstore.models.UserModel;
import com.bookstore.models.BookModel.Status;
import com.github.javafaker.Book;

/**
 *
 * @author yanti
 */
public class AddProductFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddProductPanel
     */
    public AddProductFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        setIsbn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        setTitle = new javax.swing.JTextField();
        Price = new javax.swing.JLabel();
        setPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        setQuantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        setPublicserId = new javax.swing.JTextField();
        namePublicser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        setAuthorId = new javax.swing.JTextField();
        nameAuthor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        setImageLink = new javax.swing.JTextField();
        ChooseLink = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        setStatus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        setDescription = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        ButtonBack = new javax.swing.JButton();
        ButtonSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setMaximumSize(new java.awt.Dimension(566, 400));
        setMinimumSize(new java.awt.Dimension(566, 400));
        setPreferredSize(new java.awt.Dimension(566, 450));
        getContentPane().setLayout(new java.awt.FlowLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add New Book ");
        jLabel1.setPreferredSize(new java.awt.Dimension(600, 25));
        getContentPane().add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setText("Isbn");
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 16));
        getContentPane().add(jLabel2);

        setIsbn.setPreferredSize(new java.awt.Dimension(200, 22));
        getContentPane().add(setIsbn);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setText("Book Title");
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 16));
        getContentPane().add(jLabel3);

        setTitle.setPreferredSize(new java.awt.Dimension(200, 22));
        getContentPane().add(setTitle);

        Price.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Price.setText("Price");
        Price.setPreferredSize(new java.awt.Dimension(200, 16));
        getContentPane().add(Price);

        setPrice.setPreferredSize(new java.awt.Dimension(200, 22));
        getContentPane().add(setPrice);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setText("Quantity");
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 16));
        getContentPane().add(jLabel4);

        setQuantity.setText("\n");
        setQuantity.setPreferredSize(new java.awt.Dimension(200, 22));
        getContentPane().add(setQuantity);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setText("Publicser id");
        jLabel5.setPreferredSize(new java.awt.Dimension(160, 16));
        getContentPane().add(jLabel5);

        setPublicserId.setText("\n");
        setPublicserId.setPreferredSize(new java.awt.Dimension(140, 22));
        setPublicserId.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent e) {
                
            }

            @Override
            public void focusLost(FocusEvent e) {
                checkPublicser();
            }
            
        });
        getContentPane().add(setPublicserId);

        namePublicser.setText("\n");
        namePublicser.setPreferredSize(new java.awt.Dimension(200, 22));
        getContentPane().add(namePublicser);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setText("Author id");
        jLabel6.setPreferredSize(new java.awt.Dimension(160, 16));
        getContentPane().add(jLabel6);

        setAuthorId.setText("\n");
        setAuthorId.setPreferredSize(new java.awt.Dimension(140, 22));
        setAuthorId.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent e) {
                
            }

            @Override
            public void focusLost(FocusEvent e) {
                checkAuthor();
            }
            
        });
        getContentPane().add(setAuthorId);

        nameAuthor.setText("\n");
        nameAuthor.setPreferredSize(new java.awt.Dimension(200, 22));
        getContentPane().add(nameAuthor);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setText("Image Link");
        jLabel7.setPreferredSize(new java.awt.Dimension(140, 16));
        getContentPane().add(jLabel7);

        setImageLink.setPreferredSize(new java.awt.Dimension(220, 22));
        getContentPane().add(setImageLink);

        ChooseLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/categories.png"))); // NOI18N
        ChooseLink.setActionCommand("+");
        ChooseLink.setPreferredSize(new java.awt.Dimension(50, 23));
        ChooseLink.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                addLinkImage();
            }
            
        });
        getContentPane().add(ChooseLink);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Status");
        jLabel8.setPreferredSize(new java.awt.Dimension(180, 16));
        getContentPane().add(jLabel8);

        setStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AVAILABLE", "UNAVAILABLE", "DELETED" }));
        getContentPane().add(setStatus);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(550, 100));

        setDescription.setColumns(20);
        setDescription.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        setDescription.setRows(5);
        setDescription.setText("vjdfvjnfvnf");
        jScrollPane1.setViewportView(setDescription);

        getContentPane().add(jScrollPane1);

        jPanel1.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 20));

        ButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/back.png"))); // NOI18N
        ButtonBack.setPreferredSize(new java.awt.Dimension(72, 23));
        jPanel1.add(ButtonBack);

        ButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/save.png"))); // NOI18N
        ButtonSave.setPreferredSize(new java.awt.Dimension(72, 23));
        ButtonSave.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                actionAdd();
            }
            
        });
        jPanel1.add(ButtonSave);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void checkPublicser(){
        if(PublisherBUS.getInstance().getModelById(Integer.parseInt(setPublicserId.getText().trim()))!=null){
            namePublicser.setText(PublisherBUS.getInstance().getModelById(Integer.parseInt(setPublicserId.getText().trim())).getName());
        }
        else{
            namePublicser.setText("");
        }
    }
    public void checkAuthor(){
        if(AuthorBUS.getInstance().getModelById(Integer.parseInt(setAuthorId.getText().trim()))!=null){
            nameAuthor.setText(AuthorBUS.getInstance().getModelById(Integer.parseInt(setAuthorId.getText().trim())).getName());
        }
        else{
            nameAuthor.setText("");
        }
    }
    public String addLinkImage(){
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String filePath = selectedFile.getAbsolutePath();
            setImageLink.setText(filePath);
            return filePath;
        }
        return null;
    }
    
    public void actionAdd(){
        Boolean checkForDuplicate = true;
        if(setIsbn.getText().trim().isEmpty())
        {
            checkForDuplicate = false;
            JOptionPane.showMessageDialog(null, "Isbn cannot be empty!");
            return;
        }
        if(setTitle.getText().trim().isEmpty())
        {
            checkForDuplicate = false;
            JOptionPane.showMessageDialog(null, "Title cannot be empty!");
            return;
        }
        if(setPrice.getText().trim().isEmpty() || !setPrice.getText().trim().matches("\\d+"))
        {
            checkForDuplicate = false;
            JOptionPane.showMessageDialog(null, "Prince is not valid!");
            return;
        }
        if(setQuantity.getText().trim().isEmpty()|| !setQuantity.getText().trim().matches("\\d+"))
        {
            checkForDuplicate = false;
            JOptionPane.showMessageDialog(null, "Quantity is not valid!");
            return;
        }
        if(setPublicserId.getText().trim().isEmpty() || !setPublicserId.getText().trim().matches("\\d+"))
        {
            checkForDuplicate = false;
            JOptionPane.showMessageDialog(null, "Publicser Id is not valid!");
            return;
        }
        if(setAuthorId.getText().trim().isEmpty() || !setAuthorId.getText().trim().matches("\\d+"))
        {
            checkForDuplicate = false;
            JOptionPane.showMessageDialog(null, "Author Id is not valid!");
            return;
        }
        if(nameAuthor.getText().trim().isEmpty() )
        {
            checkForDuplicate = false;
            JOptionPane.showMessageDialog(null, "This author's name can't be found, please enter the author's name to add it!");
            return;
        }
        if(namePublicser.getText().trim().isEmpty() )
        {
            checkForDuplicate = false;
            JOptionPane.showMessageDialog(null, "This publisher's name could not be found, please enter the publisher's name to add it!");
            return;
        }


        if(BookBUS.getInstance().checkForDuplicate(Arrays.asList(setIsbn.getText()), new String[] {"isbn"})){
            checkForDuplicate = false;
            JOptionPane.showMessageDialog(null, "Isbn already exists!");
            return;
        }
        if(BookBUS.getInstance().checkForDuplicate(Arrays.asList(setTitle.getText()), new String[] {"title"})){
            checkForDuplicate = false;
            JOptionPane.showMessageDialog(null, "Title already exists!");
            return;
        }


        if(checkForDuplicate) {
            Status newStatus = Status.valueOf(setStatus.getSelectedItem().toString().toUpperCase());
            BookBUS.getInstance().addModel(new BookModel(setIsbn.getText(), setTitle.getText(), setDescription.getText(), setImageLink.getText(), Integer.parseInt(setPrice.getText()), Integer.parseInt(setQuantity.getText().trim()), newStatus, Integer.parseInt(setPublicserId.getText().trim()), Integer.parseInt(setAuthorId.getText().trim())));
            JOptionPane.showMessageDialog(null, "Completed!");
        }
    }
    

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonSave;
    private javax.swing.JButton ChooseLink;
    private javax.swing.JLabel Price;
    private javax.swing.JComboBox<String> setStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameAuthor;
    private javax.swing.JTextField namePublicser;
    private javax.swing.JTextField setAuthorId;
    private javax.swing.JTextArea setDescription;
    private javax.swing.JTextField setImageLink;
    private javax.swing.JTextField setIsbn;
    private javax.swing.JTextField setPrice;
    private javax.swing.JTextField setPublicserId;
    private javax.swing.JTextField setQuantity;
    private javax.swing.JTextField setTitle;
    // End of variables declaration//GEN-END:variables
}
