/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bookstore.gui.form.admin.component.book;


import javax.swing.ImageIcon;
import javax.swing.JTextField;

/**
 *
 * @author yanti
 */
public class BookProductPanel extends javax.swing.JPanel {

  private JTextField isbnBook;

  /**
   * Creates new form BookProductPanel
   */
  public BookProductPanel(String isbn,String title,String description,String image,int price,int quantity,Enum status,int publisher_id,int author_id) {
    initComponents(isbn,title,description,image,price,quantity,status,publisher_id,author_id);
    setImage(image);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getTitle = new javax.swing.JLabel();
        GetImageBook = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ButtonDetail = new javax.swing.JButton();
        checkBox = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(199, 333));
        setMinimumSize(new java.awt.Dimension(199, 333));
        setPreferredSize(new java.awt.Dimension(199, 333));

        getTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getTitle.setText("title");
        add(getTitle);

        GetImageBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GetImageBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bookstore/gui/admin/imageBook/imagebook1.png"))); // NOI18N
        GetImageBook.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        GetImageBook.setPreferredSize(new java.awt.Dimension(200, 260));
        add(GetImageBook);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        ButtonDetail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonDetail.setText("Detail");
        jPanel1.add(ButtonDetail);

        add(jPanel1);
        add(checkBox);
    }// </editor-fold>//GEN-END:initComponents

  public void setImage(String image) {
    GetImageBook.setIcon(new javax.swing.ImageIcon(image));
    ImageIcon icon = (ImageIcon) GetImageBook.getIcon();
    int imageLoadStatus = icon.getImageLoadStatus();
    if (imageLoadStatus != 8) {
      GetImageBook.setIcon(
        new javax.swing.ImageIcon(
          getClass().getResource("/resources/images_products/imagenull.png")
        )
      );
    }
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDetail;
    private javax.swing.JLabel GetImageBook;
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JLabel getTitle;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
