/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bookstore.gui.form.admin.component.book;

import com.bookstore.bus.AuthorBUS;
import com.bookstore.bus.BookBUS;
import com.bookstore.bus.PublisherBUS;
import com.bookstore.models.BookModel;
import com.bookstore.models.BookModel.Status;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;

/**
 *
 * @author yanti
 */
public class BookDetailFrame extends javax.swing.JFrame {

  /**
   * Creates new form BookDetailFrame
   *
   */
  public BookDetailFrame(
      String isbn,
      String title,
      String description,
      String image,
      int price,
      int quantity,
      Enum status,
      int publisher_id,
      int author_id) {
    initComponents(
        isbn,
        title,
        description,
        image,
        price,
        quantity,
        status,
        publisher_id,
        author_id);
    setStatus(status);
    setImage(image);
    setTitle("Book");
    setLocationRelativeTo(null);
    setResizable(false);
    this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   *
   * @throws SQLException
   * @throws ClassNotFoundException
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents(String isbn,
      String title,
      String description,
      String image,
      int price,
      int quantity,
      Enum status,
      int publisher_id,
      int author_id) {

    jPanel3 = new javax.swing.JPanel();
    getImageBook = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    getBookTitle = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    getBookPrice = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    getStatus = new javax.swing.JComboBox<>();
    jLabel2 = new javax.swing.JLabel();
    getBookIsbn = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    getAvailableQuantity = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    getAuthorName = new javax.swing.JTextField();
    jtextfield = new javax.swing.JLabel();
    setPublicser = new javax.swing.JTextField();
    jPanel1 = new javax.swing.JPanel();
    jLabel6 = new javax.swing.JLabel();
    jPanel4 = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();
    ButtonBack = new javax.swing.JButton();
    ButtonSave = new javax.swing.JButton();
    jScrollPane2 = new javax.swing.JScrollPane();
    getDescription = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setPreferredSize(new java.awt.Dimension(900, 539));
    getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

    jPanel3.setPreferredSize(new java.awt.Dimension(858, 280));
    jPanel3.setLayout(new java.awt.BorderLayout());

    getImageBook.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    getImageBook.setEnabled(false);
    getImageBook.setPreferredSize(new java.awt.Dimension(200, 16));
    jPanel3.add(getImageBook, java.awt.BorderLayout.LINE_START);

    jPanel2.setPreferredSize(new java.awt.Dimension(655, 300));
    jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    getBookTitle.setEditable(false);
    getBookTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    getBookTitle.setText(title);
    getBookTitle.setPreferredSize(new java.awt.Dimension(600, 26));
    jPanel2.add(getBookTitle);

    jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel5.setText("Price:");
    jLabel5.setPreferredSize(new java.awt.Dimension(100, 25));
    jPanel2.add(jLabel5);

    getBookPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    getBookPrice.setForeground(new java.awt.Color(255, 51, 51));
    getBookPrice.setText(""+price);
    jPanel2.add(getBookPrice);

    jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel4.setText("Status:");
    jLabel4.setPreferredSize(new java.awt.Dimension(290, 25));
    jPanel2.add(jLabel4);

    getStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    getStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AVAILABLE", "UNAVAILABLE", "DELETED" }));
    jPanel2.add(getStatus);

    jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel2.setText("ISBN");
    jLabel2.setPreferredSize(new java.awt.Dimension(150, 25));
    jPanel2.add(jLabel2);

    getBookIsbn.setEditable(false);
    getBookIsbn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    getBookIsbn.setText(""+isbn);
    getBookIsbn.setPreferredSize(new java.awt.Dimension(290, 31));
    jPanel2.add(getBookIsbn);

    jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel3.setText("Available Quantity");
    jLabel3.setPreferredSize(new java.awt.Dimension(230, 25));
    jPanel2.add(jLabel3);

    getAvailableQuantity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    getAvailableQuantity.setText(""+quantity);
    getAvailableQuantity.setPreferredSize(new java.awt.Dimension(290, 31));
    jPanel2.add(getAvailableQuantity);

    jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel7.setText("Author");
    jLabel7.setPreferredSize(new java.awt.Dimension(230, 25));
    jPanel2.add(jLabel7);

    getAuthorName.setEditable(false);
    getAuthorName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    getAuthorName.setText(AuthorBUS.getInstance().getModelById(author_id).getName());
    getAuthorName.setPreferredSize(new java.awt.Dimension(290, 31));
    jPanel2.add(getAuthorName);

    jtextfield.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jtextfield.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jtextfield.setText("Publicser");
    jtextfield.setPreferredSize(new java.awt.Dimension(230, 25));
    jPanel2.add(jtextfield);

    setPublicser.setEditable(false);
    setPublicser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    setPublicser.setText(PublisherBUS.getInstance().getModelById(publisher_id).getName());
    setPublicser.setPreferredSize(new java.awt.Dimension(290, 31));
    jPanel2.add(setPublicser);

    jPanel3.add(jPanel2, java.awt.BorderLayout.CENTER);

    getContentPane().add(jPanel3);

    jPanel1.setPreferredSize(new java.awt.Dimension(863, 220));
    jPanel1.setLayout(new java.awt.BorderLayout());

    jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel6.setText("Description:");
    jPanel1.add(jLabel6, java.awt.BorderLayout.PAGE_START);

    jPanel4.setLayout(new java.awt.BorderLayout());

    jPanel5.setPreferredSize(new java.awt.Dimension(863, 50));
    jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

    ButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/back.png"))); // NOI18N
    ButtonBack.setPreferredSize(new java.awt.Dimension(80, 30));
    ButtonBack.addActionListener(new ActionListener() {

      @Override
      public void actionPerformed(ActionEvent e) {
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(ButtonBack);
          frame.dispose();
      }
      
    });
    jPanel5.add(ButtonBack);

    ButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/save.png"))); // NOI18N
    ButtonSave.setPreferredSize(new java.awt.Dimension(80, 30));
    ButtonSave.addActionListener(new ActionListener() {

      @Override
      public void actionPerformed(ActionEvent e) {
       save(isbn, title, description, image, price, quantity, status, publisher_id, author_id);
      }
      
    });
    jPanel5.add(ButtonSave);

    jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_END);

    getDescription.setColumns(5);
    getDescription.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
    getDescription.setLineWrap(true);
    getDescription.setRows(5);
    getDescription.setText(description);
    jScrollPane2.setViewportView(getDescription);

    jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

    jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

    getContentPane().add(jPanel1);

    pack();
  }// </editor-fold>//GEN-END:initComponents


  public void setStatus(Enum status) {
    int index = -1;
    switch (status.toString()) {
      case "AVAILABLE" -> {
        index = 0;
      }
      case "UNAVAILABLE" -> {
        index = 1;
      }
      case "DELETED" -> {
        index = 2;
      }
    }
    getStatus.setSelectedIndex(index);
  }

  public void save(String isbn,
      String title,
      String description,
      String image,
      int price,
      int quantity,
      Enum status,
      int publisher_id,
      int author_id) {
    Object selectedStatusItem = getStatus.getSelectedItem();
    if (selectedStatusItem != null) {
      String statusString = selectedStatusItem.toString().toUpperCase();
      Status newStatus = Status.valueOf(statusString);
      int newPrice = Integer.valueOf(getBookPrice.getText());
      int newQuantity = Integer.valueOf(getAvailableQuantity.getText());
      BookModel newBook = new BookModel(
          isbn,
          title,
          getDescription.getText(),
          image,
          newPrice,
          newQuantity,
          newStatus,
          publisher_id,
          author_id);
      int confirm = JOptionPane.showConfirmDialog(
          null,
          "Do you want to continue?",
          "Confirmation",
          JOptionPane.YES_NO_OPTION);
      if (confirm == JOptionPane.YES_OPTION) {
        BookBUS.getInstance().updateModel(newBook);
      }
    }
    for (Frame window : JFrame.getFrames()) {
      if (window instanceof JFrame) {
        JFrame frame = (JFrame) window;
        frame.setVisible(false);
        frame.dispose();
        frame.setVisible(true);
      }
    }
  }
  public void setImage(String image) {
    getImageBook.setIcon(new javax.swing.ImageIcon(image));
    ImageIcon icon = (ImageIcon) getImageBook.getIcon();
    int imageLoadStatus = icon.getImageLoadStatus();
    if (imageLoadStatus != 8) {
      getImageBook.setIcon(
        new javax.swing.ImageIcon(
          getClass().getResource("/resources/images_products/imagenull.png")
        )
      );
    }
  }

  
  /**
   * @param args the command line arguments
   */

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton ButtonBack;
  private javax.swing.JButton ButtonSave;
  private javax.swing.JTextField getAuthorName;
  private javax.swing.JTextField getAvailableQuantity;
  private javax.swing.JTextField getBookIsbn;
  private javax.swing.JTextField getBookPrice;
  private javax.swing.JTextField getBookTitle;
  private javax.swing.JTextArea getDescription;
  private javax.swing.JLabel getImageBook;
  private javax.swing.JComboBox<String> getStatus;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JLabel jtextfield;
  private javax.swing.JTextField setPublicser;
  // End of variables declaration//GEN-END:variables
}
