/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bookstore.gui.customer.formCustomer;

import java.awt.GridLayout;
import java.sql.SQLException;
import java.util.List;

import javax.swing.JButton;

import com.bookstore.bus.BookBUS;
import com.bookstore.model.BookModel;

/**
 *
 * @author Danh
 */
public class BrowseProductPanel extends javax.swing.JPanel {

  /**
   * Creates new form BrowswProductUI
   */
  public BrowseProductPanel() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    sortByComboBox = new javax.swing.JComboBox<>();
    searchBookTxtFld = new javax.swing.JTextField();
    searchBtn = new javax.swing.JButton();
    showBookListPanel = new javax.swing.JPanel();

    jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
    jLabel1.setText("Sort by:");

    sortByComboBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
    sortByComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[] { "Recommendation", "price: low -> high", "price: high -> low" }));
    sortByComboBox.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        try {
          sortByComboBoxActionPerformed(evt);
        } catch (ClassNotFoundException | SQLException e) {
          // TODO Auto-generated catch block
          e.printStackTrace();
        }
      }
    });

    searchBookTxtFld.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    searchBookTxtFld.setText("Search anything here..");
    searchBookTxtFld.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        searchBookTxtFldActionPerformed(evt);
      }
    });

    searchBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
    searchBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        searchBtnActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sortByComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBookTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 450,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE)
                .addContainerGap()));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchBookTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(sortByComboBox)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE)
            .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));

    showBookListPanel.setMinimumSize(new java.awt.Dimension(821, 482));
    showBookListPanel.setPreferredSize(new java.awt.Dimension(821, 482));
    showBookListPanel.addAncestorListener(new javax.swing.event.AncestorListener() {
      public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
        showBookListPanelAncestorAdded(evt);
      }

      public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
      }

      public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
      }
    });
    showBookListPanel.setLayout(new java.awt.GridLayout());

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE))
            .addComponent(showBookListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showBookListPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
  }// </editor-fold>//GEN-END:initComponents

  private void sortByComboBoxActionPerformed(java.awt.event.ActionEvent evt)
      throws ClassNotFoundException, SQLException {

    BookModel bookModel = new BookModel();
    bookModel.setTitle("abcd");
    bookModel.setAuthorId(12345);
    bookModel.setIsbn("19823719");
    bookModel.setQuantity(20);
    //setLayout(new GridLayout(4, 5, 10, 10));
    for (int i = 1; i <= 20; i++) {
      // add(bookProductPanel);
      JButton button = new JButton("Nút " + i);
      showBookListPanel.add(button);
    }

  }

  private void searchBookTxtFldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_searchBookTxtFldActionPerformed
    // TODO add your handling code here:
  }

  private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_searchBtnActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_searchBtnActionPerformed

  private void showBookListPanelAncestorAdded(javax.swing.event.AncestorEvent evt) {// GEN-FIRST:event_showBookListPanelAncestorAdded
    // TODO add your handling code here:
  }// GEN-LAST:event_showBookListPanelAncestorAdded

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JTextField searchBookTxtFld;
  private javax.swing.JButton searchBtn;
  private javax.swing.JPanel showBookListPanel;
  private javax.swing.JComboBox<String> sortByComboBox;
  // End of variables declaration//GEN-END:variables
}
