/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bookstore.gui.components.orders;

import com.bookstore.bus.OrderBUS;
import com.bookstore.bus.UserBUS;
import com.bookstore.models.OrderModel;
import com.bookstore.models.UserModel;
import java.awt.GridLayout;
import java.util.List;

/**
 *
 * @author yanti
 */
public class OrderListPanel extends javax.swing.JPanel {

  private static OrderListPanel instance;

  /**
   * Creates new form OrderPanel
   */
  public OrderListPanel() {
    initComponents();
    addTable();
  }

  public static OrderListPanel getInstance() {
    if (instance == null) {
      instance = new OrderListPanel();
    }
    return instance;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */

  // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        titlePanel = new javax.swing.JLabel();
        contend = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ButtonExport = new javax.swing.JButton();
        ButtonInport = new javax.swing.JButton();
        ButtonCreate = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();
        tableContend = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JPanel();
        headerTable = new javax.swing.JPanel();
        serialText = new javax.swing.JLabel();
        idText = new javax.swing.JLabel();
        customerText = new javax.swing.JLabel();
        employeeText = new javax.swing.JLabel();
        totalText = new javax.swing.JLabel();
        statusText = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(702, 444));
        setLayout(new java.awt.BorderLayout());

        titlePanel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        titlePanel.setForeground(new java.awt.Color(255, 0, 51));
        titlePanel.setText("List Order");
        add(titlePanel, java.awt.BorderLayout.NORTH);

        contend.setLayout(new java.awt.BorderLayout());

        buttonPanel.setLayout(new java.awt.BorderLayout());

        ButtonExport.setText("Xuất File");
        ButtonExport.setToolTipText("");

        ButtonInport.setText("Nhập File");

        ButtonCreate.setText("Create");

        ButtonDelete.setText("Delete");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(ButtonExport)
                .addGap(18, 18, 18)
                .addComponent(ButtonInport)
                .addGap(18, 18, 18)
                .addComponent(ButtonCreate)
                .addGap(18, 18, 18)
                .addComponent(ButtonDelete)
                .addGap(0, 39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(ButtonExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonInport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        buttonPanel.add(jPanel3, java.awt.BorderLayout.LINE_END);

        contend.add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        tableContend.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout tableLayout = new javax.swing.GroupLayout(table);
        table.setLayout(tableLayout);
        tableLayout.setHorizontalGroup(
            tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        tableLayout.setVerticalGroup(
            tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        scrollPane.setViewportView(table);

        tableContend.add(scrollPane, java.awt.BorderLayout.CENTER);

        headerTable.setPreferredSize(new java.awt.Dimension(611, 53));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWeights = new double[] {1.0, 2.0, 3.0, 4.0, 5.0, 6.0};
        headerTable.setLayout(jPanel1Layout);

        serialText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        serialText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        serialText.setText("Serial");
        serialText.setMaximumSize(new java.awt.Dimension(12, 18));
        serialText.setMinimumSize(new java.awt.Dimension(17, 18));
        serialText.setName(""); // NOI18N
        serialText.setPreferredSize(new java.awt.Dimension(20, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        headerTable.add(serialText, gridBagConstraints);

        idText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idText.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.ipady = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 29, 0, 0);
        headerTable.add(idText, gridBagConstraints);

        customerText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customerText.setText("Customer");
        customerText.setMinimumSize(new java.awt.Dimension(15, 20));
        customerText.setPreferredSize(new java.awt.Dimension(65, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 105;
        gridBagConstraints.ipady = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 27, 0, 0);
        headerTable.add(customerText, gridBagConstraints);

        employeeText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        employeeText.setText("Employee");
        employeeText.setMinimumSize(new java.awt.Dimension(15, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.ipady = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 32, 0, 0);
        headerTable.add(employeeText, gridBagConstraints);

        totalText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalText.setText("Total");
        totalText.setMinimumSize(new java.awt.Dimension(13, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 67;
        gridBagConstraints.ipady = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 0, 0);
        headerTable.add(totalText, gridBagConstraints);

        statusText.setText("Status");
        statusText.setMinimumSize(new java.awt.Dimension(69, 16));
        statusText.setPreferredSize(new java.awt.Dimension(69, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 35;
        headerTable.add(statusText, gridBagConstraints);

        tableContend.add(headerTable, java.awt.BorderLayout.PAGE_START);

        contend.add(tableContend, java.awt.BorderLayout.CENTER);

        add(contend, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

  public void addTable() {
    int Serial = 0;
    List<OrderModel> listOrder = OrderBUS.getInstance().getAllModels();
    table.setLayout(new GridLayout(0, 1, 5, 5));
    for (OrderModel order : listOrder) {
      if (!order.getStatus().toString().equals("BANNED")) {
        ItemOrderPanel orderForm = new ItemOrderPanel(
          Serial,
          order.getId(),
          order.getCartId(),
          order.getCustomerId(),
          order.getEmployeeId(),
          order.getTotal(),
          order.getCreatedAt(),
          order.getUpdatedAt(),
          order.getStatus()
        );
        table.add(orderForm);
        Serial = Serial + 1;
      }
    }
  }

  public void receiveValue(String value) {
    int Serial = 0;
    List<UserModel> customerList = UserBUS
      .getInstance()
      .searchModel(value, new String[] { "name" });
    table.removeAll();
    table.setLayout(new GridLayout(0, 1, 10, 10));
    for (UserModel customer : customerList) {
      List<OrderModel> listOrder = OrderBUS
        .getInstance()
        .searchModel(
          String.valueOf(customer.getId()),
          new String[] { "customer_id" }
        );
      for (OrderModel order : listOrder) {
        if (!order.getStatus().toString().equals("BANNED")) {
          ItemOrderPanel orderForm = new ItemOrderPanel(
            1,
            order.getId(),
            order.getCartId(),
            order.getCustomerId(),
            order.getEmployeeId(),
            order.getTotal(),
            order.getCreatedAt(),
            order.getUpdatedAt(),
            order.getStatus()
          );
          table.add(orderForm);
          Serial = Serial + 1;
        }
      }
    }
    table.revalidate();
    table.repaint();
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCreate;
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonExport;
    private javax.swing.JButton ButtonInport;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel contend;
    private javax.swing.JLabel customerText;
    private javax.swing.JLabel employeeText;
    private javax.swing.JPanel headerTable;
    private javax.swing.JLabel idText;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel serialText;
    private javax.swing.JLabel statusText;
    private javax.swing.JPanel table;
    private javax.swing.JPanel tableContend;
    private javax.swing.JLabel titlePanel;
    private javax.swing.JLabel totalText;
    // End of variables declaration//GEN-END:variables
}
