/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bookstore.gui.form.admin.component.bookListComponent;

import java.sql.SQLException;

import javax.swing.JTextField;

/**
 *
 * @author yanti
 */
public class BookProductPanel extends javax.swing.JPanel {

    private JTextField isbnBook;

    /**
     * Creates new form BookProductPanel
     */
    public BookProductPanel(String isbn, String title, String description, String image, int price, int quantity,
            Enum status, int publisher_id, int author_id) {
        initComponents(isbn, title, description, image, price, quantity, status, publisher_id, author_id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents(String isbn, String title, String description, String image, int price, int quantity,
            Enum status, int publisher_id, int author_id) {

        GetImageBook = new javax.swing.JLabel();
        ButtonDetail = new javax.swing.JButton();
        checkBox = new javax.swing.JCheckBox();
        setName = new javax.swing.JTextField();
        isbnBook = new javax.swing.JTextField();

        isbnBook.setText("" + isbn);
        add(isbnBook);

        // setBackground(new java.awt.Color(153, 255, 51));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(201, 246));

        GetImageBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GetImageBook.setIcon(new javax.swing.ImageIcon(getClass().getResource(image))); // NOI18N
        GetImageBook.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ButtonDetail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonDetail.setText("Detail");
        ButtonDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookDetailFrame bookDetailFrame;
                bookDetailFrame = new BookDetailFrame(isbn, title, description, image, price, quantity, status,
                        publisher_id, author_id);
                bookDetailFrame.setVisible(true);

            }
        });

        setName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        setName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        setName.setText(title);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(GetImageBook, javax.swing.GroupLayout.Alignment.LEADING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                .createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(checkBox)
                                                .addGap(18, 18, 18)
                                                .addComponent(ButtonDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 99,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(setName, javax.swing.GroupLayout.PREFERRED_SIZE, 168,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(setName, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GetImageBook, javax.swing.GroupLayout.PREFERRED_SIZE, 158,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ButtonDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(checkBox))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDetail;
    private javax.swing.JLabel GetImageBook;
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JTextField setName;
    // End of variables declaration//GEN-END:variables
}
